import { IWorkbookData, IWorksheetData, LocaleType } from "@univerjs/core";

export const EMPTY_DATA_SHEET: IWorksheetData = {
  type: 0,
  name: "Sheet1",
  id: "sheet-100",
  tabColor: "",
  hidden: 0,
  rowCount: 1000,
  columnCount: 27,
  zoomRatio: 1,
  freeze: {
    xSplit: 0,
    ySplit: 0,
    startRow: -1,
    startColumn: -1,
  },
  scrollTop: 0,
  scrollLeft: 0,
  defaultColumnWidth: 73,
  defaultRowHeight: 19,
  mergeData: [],
  hideRow: [],
  hideColumn: [],
  cellData: {},
  rowData: {},
  columnData: {},
  status: 1,
  showGridlines: 1,
  rowHeader: {
    width: 46,
    hidden: 0,
  },
  columnHeader: {
    height: 20,
    hidden: 0,
  },
  selections: ["A1"],
  rightToLeft: 0,
  pluginMeta: {},
};
